# Generated by Django 3.1.5 on 2021-01-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minister', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
